# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Aylin Delacruz | Miss Game and Culture
email: asdelacruz.94@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hello World!
  On my website, I discuss topics surrounding games and culture, whether it be concerning
  women in the games industry or ranking the top ten Legend of Zelda titles.
  I also have examples of my previous projects 
  and information about myself, my interests, and past experiences.
  Check out my most recent project: www.tuckerstemple.com 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://aylindelacruz.com" # the base hostname & protocol for your site
twitter_username: aylinselena_
github_username:  asdelacr
linkedin_username: in/aylindelacruz

# Build settings
markdown: kramdown
